#!/usr/bin/env bash

THEME_DIR="$HOME/.config/dotmgr/themes"
PAPER="$THEME_DIR/_current/paper.conf"

wall_path="$1"

# Safety check
if [[ -z "$wall_path" ]]; then
  echo "Usage: $0 /absolute/or/~/path/to/wallpaper"
  exit 1
fi

# Expand ~ manually so hyprpaper is happy
wall_path="$(realpath -m "$wall_path")"

# Recreate paper.conf
rm -f "$PAPER"

cat >"$PAPER" <<EOF
# Auto-generated by dotmgr
splash = false

wallpaper {
    monitor =        # wildcard: applies to all monitors
    path = $wall_path
    fit_mode = cover
}
EOF

# Reload hyprpaper (v0.8+ way)
hyprctl hyprpaper reload

# Restart eww so it layers correctly
eww --restart open bar
