#!/usr/bin/env bash
#  scribe - ANSI-colored logging system
set -e

RESET="\033[0m"
BOLD="\033[1m"

# Colors
FG_RED="\033[31m"
FG_GREEN="\033[32m"
FG_YELLOW="\033[33m"
FG_BLUE="\033[34m"
FG_MAGENTA="\033[35m"
FG_CYAN="\033[36m"
FG_WHITE="\033[37m"

log() {
    local level="$1"
    shift
    local message="$*"
    local color

    case "$level" in
        info)    color="$FG_RED";;
	success) color="$FG_GREEN";;
	warn)    color="$FG_YELLOW";;
	error)   color="$FG_RED";;
	action)  color="$FG_CYAN";;
	debug)   color="$FG_MAGENTA";;
	*)       color="$FG_WHITE";;
    esac

    echo -e "${color}${message}${RESET}"
}
