#!usr/bin/env bash

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo -e """\033[33m
    __ __                __                 
   / //_/__  __  _______/ /_____  ____  ___ 
  / ,< / _ \\/ / / / ___/ __/ __ \\/ __ \\/ _ \\
 / /| /  __/ /_/ (__  ) /_/ /_/ / / / /  __/
/_/ |_\\___/\\__, /____/\\__/\\____/_/ /_/\\___/ 
          /____/                            
\033[0m"""

# Call Submodules
"$SCRIPT_DIR/mason" "$@"

# Future:
# ./smith
# ./pillar
# ./vault

hyprctl reload > /dev/null

echo -e "\033[32mSuccess\033[0m"
