#!/usr/bin/env bash

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/scribe"

log warn """${BOLD}
    __ __                __                 
   / //_/__  __  _______/ /_____  ____  ___ 
  / ,< / _ \\/ / / / ___/ __/ __ \\/ __ \\/ _ \\
 / /| /  __/ /_/ (__  ) /_/ /_/ / / / /  __/
/_/ |_\\___/\\__, /____/\\__/\\____/_/ /_/\\___/ 
          /____/                            
"""

# TODO: Determine the order that these need to be called
MASON="$SCRIPT_DIR/mason"
PILLAR="$SCRIPT_DIR/pillar"
QUENCH="$SCRIPT_DIR/quench"
SMITH="$SCRIPT_DIR/smith"

if [ -f "$MASON" ]; then
    chmod +x "$MASON"
    "$MASON" "$@"
fi

if [ -f "$SMITH" ]; then
    chmod +x "$SMITH"
    "$SMITH" "$@"
fi

if [ -f "$PILLAR" ]; then
    chmod +x "$PILLAR"
    "$PILLAR" "$@"
fi

if [ -f "$QUENCH" ]; then
    chmod +x "$QUENCH"
    "$QUENCH" "$@"
fi

log success "Success"
