#!/usr/bin/env bash
# Scripts Installer

set -e

MAX_DIR_NAME_LENGTH=10

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/scribe"

dry_run="0"
failed="0"

if [ -z "$XDG_CONFIG_HOME" ]; then
  log note "XDG_CONFIG_HOME not set, defaulting to ~/.config"
  CONFIG_HOME="$HOME/.config"
else
  CONFIG_HOME="$XDG_CONFIG_HOME"
fi

if [ -z "$SCRIPT_BIN" ]; then
  log fatal "Environment variable \$SCRIPT_DIR must be set"
  failed="1"
fi

if [ "$failed" -eq "1" ]; then
  log error "smith setup aborted"
  exit 1
fi

copy_with_prefix() {
  local src_dir="$1"
  local dest_dir="$2"
  local prefix
  prefix=$(basename "${src_dir%/}")

  find "$src_dir" -maxdepth 1 -type f | while read -r file; do
    local filename=$(basename "$file")

    local name_no_ext="${filename%.*}"

    local dest_file="${dest_dir%/}/${prefix}_${name_no_ext}"

    printf -v padded_filename "%-${MAX_DIR_NAME_LENGTH}s" "${prefix}_${name_no_ext}"

    cp "$file" "$dest_file"
    chmod +x "$dest_file"
    log info "Copied file: $padded_filename -> $dest_dir/"
  done
}

log action "Validating directories"
mkdir -p "$HOME/.local/bin"

log action "Beginning shell scripts setup from: $DOTFILES"
copy_with_prefix "$DOTFILES/scripts/anyrun" "$SCRIPT_BIN"
